### ISSUE TITLE
HD64180: CPIR/CPDR命令で比較の一致による終了がない?

### ISSUE THREAD

**Issue by ao-kenji** [isaki68k/nono-issue#148]
HD64180のCPIR/CPDR命令で、A == (HL) の時にリピートを終了する処理が不足しているのではないでしょうか。
hd64180/hd64180ops.cpp のREPEAT_UNTILマクロを見ると BC == 0 になった時のみリピートを終了するように読めました。

**Comment by ao-kenji** [comment]
補足: FUZIXで使用しているZ80のライブラリでは strlen() がCPIRで実装されているのですが、nonoで動かしたときに strlen("/init") の返り値が -1 になってしまうことから気づきました。
https://github.com/EtchedPixels/Fuzix-Compiler-Kit/blob/main/supportz80/_strlen.s

**Comment by isaki68k** [comment]
お手数おかけしております。以下のパッチで直ると思いますので試してもらえますか。
http://www.pastel-flower.jp/~isaki/NetBSD/patch/nono-20241112-cpir.diff

**Comment by ao-kenji** [comment]
パッチをあてた nono で、CPIR による実装の strlen() が正しく動くことを確認しました。ありがとうございます!

**Comment by isaki68k** [comment]
ありがとうございます。次リリースに入れます。
