### ISSUE TITLE
debugger: cmd_m ATCが更新されたときに反映されない

### ISSUE THREAD

**Issue by moveccr** [isaki68k/nono-issue#25]
m コマンドで行うメモリダンプは、一度 m コマンドで表示したアドレスの変換をキャッシュしている。
しかしゲストによって ATC が更新されてもキャッシュとの同期が取れていないので
表示されるアドレスが変更前のままになってしまうバグ。

**Comment by isaki68k** [comment]
ac5dd5f1 (2020-11-13) でたぶん修正できてると思う。
