### ISSUE TITLE
debugger: d,m などで前回アドレスの s/u を保存していない

### ISSUE THREAD

**Issue by moveccr** [isaki68k/nono-issue#27]
スーパバイザ状態のとき、

```shell
>d u:12345678
12345678:abcdef01 .....
>d
12345788=PA ....
```
のように前回ユーザアドレスを指定したのに継続するスーパバイザアドレスとみなされる。
ユーザ状態の場合は s: でスーパバイザ指定しても継続するユーザアドレスとみなされる。

**Comment by isaki68k** [comment]
1911156a (2020-11-12) で修正。
