### ISSUE TITLE
debugger:m88k m コマンドは常に命令ATCを見ている

### ISSUE THREAD

**Issue by moveccr** [isaki68k/nono-issue#28]
どうなんこれ。
d は命令 ATC を常に見ればいいが、m はデフォルトではデータ ATC を見てほしい。
別のコマンドかオプションかで m コマンドの命令 ATC 版を用意するべきか？

**Comment by isaki68k** [comment]
70365e28 (2020-11-13) で修正。
とりあえず m はデータのほうを見るようにした。
根本的にはもうちょっと考える。
