### ISSUE TITLE
LUNA内蔵ROMのプロンプトが表示されない

### ISSUE THREAD

**Issue by moveccr** [isaki68k/nono-issue#31]
@arakiken

1)nonoの内蔵ROM使用で、初めてnonoを起動すると、0.0.3では、NVRAM Initializedというメッセージとプロンプトが表示されるのですが、0.1.4だと何も表示されませんでした(NetBSD9.0でも同じ)。http://mlterm.sf.net/nono-0.1.4-fixnvraminit.patch のようにConsoleUpdate()を追加するとちゃんと表示されました。

**Comment by isaki68k** [comment]
a2a6c1bf (2020/11/23) で修正。
この辺もう少し見直す。
