### ISSUE TITLE
キー入力を取りこぼす

### ISSUE THREAD

**Issue by moveccr** [isaki68k/nono-issue#32]
@arakiken

2)多分速度の遅いマシンで動かしているからだと思いますが、vm/lunakbd.cppで、MakeKey()→KeyboardCallback()→BreakKey()→KeyboardCallback()ではなく、MakeKey()→BreakKey()→KeyboardCallback() という順番で実行され、BreakKey()に渡されるキーコードがkey_event.Start()されないことにより、キーを一度押しただけで、キーが押しっぱなしの状態になってしまいました。やむをえず http://mlterm.sf.net/nono-0.1.4-fixkey.patch のように修正しました。本来どう直すべきか理解していない(直すべきではないのかもしれません)のですが、もし何か分かりましたら、お教えいただけると幸いです。

**Comment by isaki68k** [comment]
メモ。キーのMake、Breakを単発イベントではなくキューにして落ちるのを防ぐか、
またVM側が速すぎて、キーリピートが効いてしまう問題はキー入力の間を実時間走行に落とすか。

**Comment by isaki68k** [comment]
ed632ae (2021-03-16) あたりまでにキューと高速走行の抑制を実装。
たぶん直るはず。
