### ISSUE TITLE
vm/upd7201 FIFOキューのデータ移動方向が逆になっているバグ

### ISSUE THREAD

**Issue by moveccr** [isaki68k/nono-issue#33]
@arakiken

3) http://mlterm.sf.net/nono-0.1.4-fixkey.patch の udp7201.cpp の修正箇所ですが、memmove()のdstとsrcが逆になっているように思ったので修正しましたが、私の勘違いでしたらすみません。

**Comment by moveccr** [comment]
ここは 3byte FIFO と決まっているので
```
chan->rxbuf[0] = chan->rxbuf[1];
chan->rxbuf[1] = chan->rxbuf[2];
```
で十分だと思う。

**Comment by isaki68k** [comment]
58235c9d (2020-11-23) で修正。
