### ISSUE TITLE
連想メモリをソフトウェアで高速に実装する

### ISSUE THREAD

**Issue by moveccr** [isaki68k/nono-issue#34]
MMU の ATC とかキャッシュの選択において、ハードウェアは連想メモリを使って高速に検索を実行しているが、
ソフトウェアでシンプルに実装すると線形探索になってとても遅い。
かといって単純なハッシュテーブルにしようにもハッシュ関数を適切かつコンパクトに設計するのは
これまた大変である。なにかいい方法がないか？

**Comment by isaki68k** [comment]
ここで想定していたものと同じかどうかは分からないが、ATCは m68k/m88k ともハッシュで高速化した。
