### ISSUE TITLE
OpenBSD/luna88k で le0: dropping chained buffer が表示される

### ISSUE THREAD

**Issue by isaki68k** [isaki68k/nono-issue#37]
https://twitter.com/ao_kenji/status/1332707393612902401
> nono(LUNA88K) on #OpenBSD/amd64, netdriverでtap(4)使えるように変更中。一応ホストマシンや同一サブネットマシンからのping(8)に反応するようになったけど、le0: dropping chained buffer が出まくっている。

OpenBSDかnonoかどっちの問題かから。

**Comment by moveccr** [comment]
このメッセージは、LANCE の受信バッファで「STP と ENP の両方が同時に立っていない」状態、すなわち 1 バッファにパケットが収まらなかったときに発生する。これは OpenBSD, NetBSD 双方で発生しうる。

LANCE 実機は 10BASE なので物理層のパケットが 1518(or 1522) バイトを超えることはなく、OS は 1536 バイトのバッファを用意しているからチェインになることはない、という理屈と推測できる。(それもどうなのか)

仮想マシンでは、
- 実際の物理層からジャンボフレームが来るケース
- lo0 などから 1500 以上の MTU でパケットが来るケース
- linux の gro によりホストOSのカーネルでパケットが集約されるケース
参考: https://www.slideshare.net/syuu1228/10-gbeio

のため、そのまま着信を受けるとチェインになる。

というわけで
- LanceDevice 側で長いパケットはドロップする
- linux については gro を off にする

により対処できた。

**Comment by moveccr** [comment]
2021/05/14 ごろの実装により修正済み。
