### ISSUE TITLE
OpenBSD/luna88k カーネルが root device 聞くところで止まる

### ISSUE THREAD

**Issue by isaki68k** [isaki68k/nono-issue#40]
たぶんNVRAMからboot deviceが拾えてないからのはず。
あおやまさんのliveimage起動で再現するはず。

**Comment by ao-kenji** [comment]
これはOpenBSD/luna88k側の課題でもあります。
昔native boot loaderがなかったころの名残で、カーネルがNVRAMのboot_unitとboot_partitionからboot deviceを判定しています。
今となっては、boot loaderでカーネル読み込んだ後にboot device情報をレジスタに入れて、カーネルへ制御を移したらよさそうですが、今度はboot loader自体がどこから起動されたのかを知る術がないので、結局どこかでNVRAMの情報が必要かなあと思っています。

**Comment by isaki68k** [comment]
ありがとうございます。OpenBSD側は確かにそうなりそうですね。
どちらにしてもnonoもNVRAMを実装してないせいで実機と違う挙動をしてしまったというところは変わらないので、なんとか早くそこまで行きたいと思っています。

**Comment by isaki68k** [comment]
2021-05-15 あたりでNVRAMの初期化を実装したので、通過するようになった。
