### ISSUE TITLE
LUNA システムクロックの実時間動作モード

### ISSUE THREAD

**Issue by moveccr** [isaki68k/nono-issue#47]
ゲストOSがSystem Clock で時間を計測しているため、VM フルスピードで実行しているとゲストの時計は進む。
実際の使用状態を考えると、ゲストから見た割り込み周期が不正確になっても、ゲストの時計がずれないほうが
都合がいいのではないか。RTC と同じようにスイッチがあるといいのかな。

VTで動作(今の挙動)
- ゲストから見た割り込み周期と回数は正確
- 実時間に対しては、フルスピードモードで進む
- VMを立ち上げ直したとき、未来のファイルができていて戸惑う

RTで動作
- ゲストから見た割り込み周期と回数は不正確(間隔が広くて、少ない)
- 実時間に対しては、同期
- デバッガで止めたらホスト時間に対してずれる。これは許容。

RTCのスイッチと共用するのもありかもしれない。「時間に関するイベントをRTで駆動」のようなスイッチにするとか。

**Comment by moveccr** [comment]
とりあえずシステムクロック実時間モードは作成したが、デバイスごとの固有の時間軸についてもっと検討が必要。キーボードはどうかとか、そういうの。

**Comment by moveccr** [comment]
X68k の MFP クロックをどうするのか。MFP は 4MHz が供給されているが VirtualTime で 4MHzなのか RealTime で 4MHz なのか。
clock-sync の設定を反映したらどうか。

**Comment by isaki68k** [comment]
LUNA 側は実装済み。x68k は別 issue にした。
