### ISSUE TITLE
x68k: キーリピートの挙動メモ

### ISSUE THREAD

**Issue by isaki68k** [isaki68k/nono-issue#49]
キーリピートについてのメモ。x68k キーボードのキーリピートを実装する時に考察すること。

https://twitter.com/kamadox/status/1393114588640464898
> キーボードのリピートの入り方
> 
> 手元のPCのUSBキーボード
> `[D↓]d___dddd[A↓]a___aaaa[A↑]________[D↑]________`
> `[D↓]d___dddd[A↓]a___aaaa[D↑]a___aaaa[A↑]________`
> 
> X68030実機
> `[D↓]d___dddd[A↓]a___aaaa[A↑]________[D↑]________`
> `[D↓]d___dddd[A↓]a___aaaa[D↑]aaaaaaaa[A↑]________`

**Comment by moveccr** [comment]
2021/06/17 実装しました。

**Comment by moveccr** [comment]
キーリピートしないキー、があったような(SHIFT,CTRL ...)

**Comment by moveccr** [comment]
ないみたいなのでクローズ。
