### ISSUE TITLE
LANCE: 送信ポーリングをなんとか端折ること

### ISSUE THREAD

**Issue by isaki68k** [isaki68k/nono-issue#52]
LANCEの送信ポーリングは1.6msecごとに起きるが、あまり意味のあることはしてないわりに(特に高速モードだと)そこそこ間隔が短く負荷が高いので、できればちょっと端折りたい。
例えば単純に間隔を広げるとか。LUNA-IのSysClkが16.6msec、CRTC2が16.2msec程度なので、これより大きい32ms, 50ms, 80ms, 160ms とか適当な値はどうか。どうせほぼ起きないので大きい値でもいいはず。
あるいは十分大きい値にしといて、このポーリングがヒットしたら次は気合を入れて1.6ms 間隔にすると、もしこの機能を使う人がいたとしても体感ほぼ分からないのでは。そしてそのうちまた伸ばすというアダプティブなのとかはどうか。

**Comment by moveccr** [comment]
1.6ms を本当は実時間で測ることができればそっちのほうが良いのではないかと思う。ただ、1.6msをどのホスト環境でも測ることが難しいので、たちまちは保留？。

**Comment by isaki68k** [comment]
負荷が高かったのはタイマー設定ミスが原因だった気がするので、これはクローズ。
