### ISSUE TITLE
JIS配列以外のキーボードをどうサポートするか？

### ISSUE THREAD

**Issue by moveccr** [isaki68k/nono-issue#64]
[https://twitter.com/ebijun/status/1407476862347923461]()

> nono 0.2.0 on pinebookpro。
LUNA88K nvramでvmunix から起動設定。
英語キーボードだと_を探してソフトキーボードから。

LUNA の場合、LUNA キーボード以外が接続されることが想定されていないため、なんらか妥協した方法を
提供するよりないか？

1. マクロキーのようなものを用意する方法
US キーボードで `_` を入力するとき、
 `↓SHIFT`  `↓-`  `↑-`  `↑SHIFT`
に対し
 `↓SHIFT`  `↓_`  `↑_`  `↑SHIFT`
を発生させる。
 ... キーを遅延させるか状態を保護するかなど、処理は大変。

2. 1:1 リマッピングで我慢する方法
 たとえば F11 は `_` キー、というように単純な 1:1 マッピングをカスタマイズできるようにする。
 ... キーの数が足らない。

3. キャラクタキーボードを作る方法
シリアルコンソールのようにキー押し下げを文字として処理し、VMへは１文字ごとに SHIFT と 文字キーの make/break を送る。
 ... SHIFT 押しっぱなしなどはできない。リピートはしないか、ホスト側のOSに依存するか。

なかなかうまい方法がない。

**Comment by isaki68k** [comment]
ver0.2.2 でキャラクタ入力モード実装。
