### ISSUE TITLE
UniOS-MachでSIO: CR0未実装コマンド6が出るようだ

### ISSUE THREAD

**Issue by isaki68k** [isaki68k/nono-issue#65]
https://twitter.com/ao_kenji/status/1408782477611528206
> NBUG例会(兼 OSC Online/Hokkaidoのセミナ)で話題になった、UniOS-Machがエミュレータで動くのか? について。
> とりあえずUniOS-MachのvmunixをOpenBSD/luna88k HDDイメージの / に置いてトライ。
> (a) 実機PROMイメージで実行 → 画像のところで止まる。UniOS-MachのHDDイメージがあればさらに進む?

コマンド6は Error Reset らしい。今まで誰も遭遇しなかったので作っていない。

**Comment by tsutsui** [comment]
NetBSD/luna68k でも `luna68k/dev/lunaws.c` の `wssoftint()` に雑に debug printf を入れて遅くした状態でキーボード連打すると
- (printf で割り込みがブロックされるので） `RxOv` が立つ
- `wsintr()` で `RxOv` が立っていると Error Reset を発行して継続する
- エラーが消えないと受信処理しない記述なので Error Reset 未実装でエラーが起きると永遠に受信できない

という動作になります。
```
	rr = getsiocsr(sio);
	if ((rr & RR_RXRDY) != 0) {
		do {
			code = sio->sio_data;
			if (rr & (RR_FRAMING | RR_OVERRUN | RR_PARITY)) {
				sio->sio_cmd = WR0_ERRRST;
				continue;
			}
			sc->sc_rxq[sc->sc_rxqtail] = code;
			sc->sc_rxqtail = OMKBD_NEXTRXQ(sc->sc_rxqtail);
		} while (((rr = getsiocsr(sio)) & RR_RXRDY) != 0);
		softint_schedule(sc->sc_si);
	}
```

Error Reset でどのビットがクリアされるのかちゃんとマニュアルを読んでませんが
コマンド6として `ResetChannel()` と同様に以下みたいにすると一応復帰します。
```
	 case 6:	// Error Reset
		// SR1 は b4-7 が '0'
		putlog(1, "CR0%s: Error Reset", chan->name);
		chan->sr1 &= ~(SIO::SR1_ENDOFFRAME | SIO::SR1_CRCERROR |
		               SIO::SR1_RXOVERRUN | SIO::SR1_PARITYERROR);
		break;
```

**Comment by isaki68k** [comment]
ありがとうございます。
昨日の夜中にマニュアルに記述を見付けてまったく同じコードを書いていました。この4ビットをクリアするで合ってるっぽいです。

5610afb4 (2021-09-16)でビットのクリアは実装。

**Comment by isaki68k** [comment]
0.2.3で直ってるはず。
