### ISSUE TITLE
LUNA88K ROM PUTC ルーチンのエミュレーション

### ISSUE THREAD

**Issue by moveccr** [isaki68k/nono-issue#68]
OpenBSD/luna88k が起動時に ROM の PUTC ルーチンで文字を表示してくる。
この表示位置は、ROM コンソールのその時点でのカーソル位置になるようだ。
下記の画像は、ROMから起動して、ROM プロンプトからブートしたときのもの。
O/ のブートローダは ROM ルーチンを使わず自前でフレームバッファに書き込んでいるため、
表示は崩れるがこれは仕様ということだろう。

![luna-cons-putc](https://user-images.githubusercontent.com/7379507/124152966-ef6dca00-dace-11eb-91fe-26659e79e2c7.png)

**Comment by tsutsui** [comment]
> O/ のブートローダは ROM ルーチンを使わず自前でフレームバッファに書き込んでいるため、
> 表示は崩れるがこれは仕様ということだろう。

- OpenBSD/luna88k のブートローダは NetBSD/luna68k から持ってきている
- LUNA (少なくとも初代LUNA の ROM Ver. 4.25) では ROMルーチンの `putchar()` と `getchar()` は
4bpp スクリーンコンソールでは動作しない
https://twitter.com/tsutsuii/status/286147612594298880
https://twitter.com/tsutsuii/status/286150216955084800
（シリアルコンソールでは使えるかもしれないが未だ確認していない）
	- ベースにした 4.4BSD/luna68k のブートローダも ROMルーチンを使っていない
- OpenBSD/luna88k では移植作業当初から（少なくともシリアルでは） ROMルーチンが使えることがわかっていたらしい
https://www.slideshare.net/ao_kenji/a-story-of-porting-openbsdluna88k

こういう流れかと

**Comment by isaki68k** [comment]
fe1da8a7 2021-10-22 で実装。

**Comment by isaki68k** [comment]
ver 0.2.4
