### ISSUE TITLE
LUNA 実機 M48T02 で CEB/CB が動作してしまう

### ISSUE THREAD

**Issue by moveccr** [isaki68k/nono-issue#75]
2018年に MK48T02 から置き換えた M48T02 で、M48T35/58 の CEB/CB (Century Enable Bit/Century Bit) が動作する。
データシート上では M48T02 は本来の MK48T02 に対して KS(キックスタート) が廃止されているだけの違いとなっているが、
実際は異なる。

M48T35/58 と同じ TIMEKEEPER ロジックが組み込まれているのではないか？
BLE/BL ビットも動作する可能性があるが、確かめる方法はたぶん無い。

**Comment by tsutsui** [comment]
あまり関係ない話で、M48T02 に置き換えた SPARCstation2 だと、PROM起動時のダイアグテストで
```
TOD Registers Test 
    FAILURE: TOD (f20007fa) Bit Failure, Exp = 000000ff, Obs = 0000007f
```
と怒られます。
https://twitter.com/tsutsuii/status/1424235329867767811

MK48T02 に戻す(?)と怒られません。
```
NVRAM Access Test 
    WARNING: TOD Oscillator NOT Running, Kickstart in Progress ... 
TOD Clock Oscillator Running
TOD Registers Test
```
https://twitter.com/tsutsuii/status/1424401295448842243

**Comment by isaki68k** [comment]
SPARCstation2 の PROM が固定の応答を期待しているようなので、+7fa の MSB を 1 固定に変更してみました。
7e1b0527 (2021-09-28)

**Comment by isaki68k** [comment]
ここのビットが立ってるとNetBSD/luna68kカーネルに
```
[   3.466675] WARNING: preposterous TOD clock time
```
と怒られるので元に戻す。SPARCstation2と何がどうなのかは分からない。
ad48892b (2021-10-05)

**Comment by tsutsui** [comment]
あー、アバウトな情報を投げてしまいすいません。
「M48T02 と MK48T02 とで異なる仕様があるようである」という程度のつもりでした。

LUNA実機の MK48T02 で挙動を見ましたが以下のようです。
* 通常動作中に `0x450007fa` (`MK48TXX_IMIN`)に `0xff` を書く
→その後読み出すと MSB (bit7) は 1 のままになり、bit0〜bit6 は min (分) のデータになる
* `0x450007f8` (`MK48TXX_ICSR`) に `0x7f` (`MK48TXX_CSR_READ` をセット) を書いた後に `0x450007fa` (`MK48TXX_IMIN`)に `0xff` を書く
→その後読み出すと `0xff` が読めて、その後 `0x450007f8` (`MK48TXX_ICSR`) に `0x3f` (`MK48TXX_CSR_READ` をクリア) を書くと MSB (bit7) は 1 のままになり、bit0〜bit6 は min (分) のデータになる

```
>450007f8  
  450007F8: 3F 05 24 18 06 09 10 51 *?.$....Q*
>450007fa;,ff
>450007f8
  450007F8: 3F 13 A4 18 06 09 10 51 *?......Q*
>450007fa;,24
>450007f8
  450007F8: 3F 26 24 18 06 09 10 51 *?&$....Q*
>450007f8;,7f
>450007fa;,ff
>450007f8
  450007F8: 7F 35 FF 18 06 09 10 51 *.5.....Q*
>450007f8;,3f
>450007f8
  450007F8: 3F 52 A4 18 06 09 10 51 *?R.....Q*
>450007fa;,24
>450007f8
  450007F8: 3F 05 25 18 06 09 10 51 *?.%....Q*
>
```

つまり、
「MK48T02 では `MK48TXX_IMIN` の bit7 に書き込むとその値がレジスタに保持されて読み出すと書き込んだ値がそのまま読める」
M48T02 では試していませんが、SS2 のダイアグログから推測すると
「M48T02 では `MK48TXX_IMIN` の bit7 に書き込んでもその値はレジスタに保持されず無視される」
ということかと。

**Comment by isaki68k** [comment]
あー、こちらこそここの更新が遅れててすみません。
その後、おそらくそういう動作なんだろうと予想して修正しておりましたが、はからずも動作確認して頂いたので助かりました。ありがとうございます(汗

**Comment by isaki68k** [comment]
本題のM48T02の CEB/CB の件は、ひとまず MK48T02 のデータシートに従って、存在してないことにし、データシート上 '0' と表記されている他のビットと同様の挙動(SRAM)にしておく。
