### ISSUE TITLE
-X でNetBSDカーネルを起動するとsavecoreで怒られる?

### ISSUE THREAD

**Issue by isaki68k** [isaki68k/nono-issue#79]
luna68k で -X netbsd でカーネルを起動すると起動中に savecore に怒られるようだ。
```
savecore: can't find device 1343/520
```
他でも再現するかとかその辺から。

**Comment by tsutsui** [comment]
これは一般的な話で「実行しているカーネル」と「 /netbsd のカーネル」とが異なるとこれが出たような……

**Comment by isaki68k** [comment]
なるほどそういう話でしたか。ありがとうございます。
ではゲストの仕様なのでクローズします。
