### ISSUE TITLE
LUNAのキーボードCAP・かな押下時に送出されるキーコードが実機と異なる?

### ISSUE THREAD

**Issue by tsutsui** [isaki68k/nono-issue#83]
LUNAエミュレーションでのソフトウェアキーボードの CAPキーとかなキーの押下時・復帰時に送出されるキーコードが
実キーボード（少なくとも初代LUNA付属の 3W4SD-098NDT）とは異なるようです。

某仕様書の動作説明記載は以下
> キースイッチを押下した時及び復旧した時にデータを送出する。
> ただし、かな及び CAPキーは復旧時にはデータを送出せず、押下時に
> 押下データと復旧データを交互に送出する。

nonoさんの実装仕様は以下?
* 押下時に 押下データ (CAP では `0x0e`) と復旧データ (CAP では `0x8e`) とを連続して送出する
* 復旧時にはデータを送出しない

実キーボードの動作仕様は以下に見える
* 押下時に LEDが消灯していれば（≒前回押下時に復旧データを送出していれば）押下データ (CAP では `0x0e`) のみを送出する
* 押下時に LEDが点灯していれば（≒前回押下時に押下データを送出していれば）復旧データ (CAP では `0x8e`) のみを送出する
	* ただし、LED点灯コマンドにより LED状態が変化していた場合は前回送信データではなくLED状態が優先する
* 復旧時にはデータを送出しない

仕様書記載の「交互に送出する」というのを素直(?)に解釈すると、実機の動きを表しているとは言えるかと。
LED点灯コマンドを送出された後の動作については明示的ではありませんが、LED点灯コマンドのところの説明には
「これ（LED点灯コマンド）に伴って、キーボード内部で記憶しているかな、CAPの押下状態も変化する」
ともあるので、「交互に」という記述は厳密には「キーボード内部で記憶している押下状態によって」という解釈かと。

---

この場合、 NetBSD/luna68k の lunaws.c のキーボード処理では上記実キーボード仕様に対応できておらず
「CAPキーとかなキーのデータについては押下・復旧いずれのデータでも 押下+復帰 の2つのコードを出す」
みたいなドライバ側改修も必要になると思われますが、これはゲスト側の問題です。
（以前から CAP の LED と CAPSLOCK の状態が一致しないことがあって 変だなー とは思っていたのですがチャタリングのせいだと思っていた）

**Comment by isaki68k** [comment]
ありがとうございます。「交互」を勘違いしてますね>当時の自分。見てみます。

**Comment by isaki68k** [comment]
e309fc7c (2021-09-16) で修正。

**Comment by tsutsui** [comment]
nono 0.2.3 + NetBSD 9.99.88 で CAP LED と かなLEDが仕様定義どおり動いているのを確認しました。ありがとうございます。
