### ISSUE TITLE
LUNAエミュレーションでの -X オプション（ホストの file をロードして実行）の仕様とドキュメントアンマッチ

### ISSUE THREAD

**Issue by tsutsui** [isaki68k/nono-issue#84]
## 概要

nono 0.2.2 時点のドキュメントでは `-X` オプションの説明は以下：
> -X file
>     ホストの file をロードして実行します。 file が相対パスの場合カレントディレクトリからのパスになります。 ファイルが gzip 圧縮されていれば自動的に展開します。 (展開後の) ファイル形式は a.out (OMAGIC) か ELF で、 実際にはブートローダとカーネル程度しか想定していません。 設定ファイルの prom-image とともに指定されると -X のほうが優先します。

一方、  `nono-0.2.2/vm/romemu_luna1.cpp` の `Luna1PROMEmuDevice::ROM_Init()` を読む限りでは実装は
「DIPSW#1-1 が UP で自動起動設定のときのみ `-X` で指定されたファイルに対して `LoadHostFile()` を呼び出し」
になっている。これは `nono-0.2.2/vm/romemu_luna88k.cpp` でも同様。

つまり、少なくとも LUNA および LUNA88K エミュでは
`-X` オプションによる file ロードは `nono.cfg` において DIPSW#1-1 を 0 と設定しているときしか動作しない。

## 修正案

ドキュメントを直すか実装も直すかという選択肢があるように思っています。

* 現状の実装が意図どおりであれば、ドキュメントに上記の実装仕様に対応する説明記載を足していただいたほうがよいかと。
* 個人的なユーザー目線で期待する仕様としては以下のいずれかのほうがよいような。
	* `-X` オプション指定時は DIPSW#1-1 の設定を無視して実行開始する
	* `-X` オプション指定、かつ DIPSW#1-1 が DOWN のときはファイルのロードとエントリポイント設定をした上で Emulated ROM のプロンプト待ちにする
	（≒ Emulated ROM での `g` コマンド実行後と同様の状態、つまり「`x` コマンドを入れればロード済みファイルを実行可能な状態」にする ）

**Comment by isaki68k** [comment]
ありがとうございます。
実装の意図としては後者(ドキュメントにDIPSWの説明が不足)でしたが、ちょっと考えてみます。

**Comment by isaki68k** [comment]
`-X` オプション指定時は DIPSW#1-1 の設定によらず実行開始する、に変更しました。
5d8acfb5 (2021-10-01)

**Comment by tsutsui** [comment]
nono 0.2.3 で DIPSW#1-1 = 0 の設定でも -X で指定したカーネルが起動するのを確認しました。ありがとうございます。
