### ISSUE TITLE
キーボードの非接続状態を実装すること

### ISSUE THREAD

**Issue by isaki68k** [isaki68k/nono-issue#86]
とりあえず設定オプションでキーボード接続状態の初期値を設定するところはいいが、X68k には何かを押しながらキーボードを差し込むと云々という機能があるので、最終的には実行時に
- 動的にキーボードを差す、抜くが出来て
- キーボードを抜いてる間もソフトウェアキーボードで(少なくとも)長押しの操作が出来る

必要があると思う。

**Comment by moveccr** [comment]
実装できたっぽい。
5a435604 2021/10/21
