### ISSUE TITLE
VirtualBox で「マウス統合」が有効なときはマウスが使えないことをマニュアルに記載する

### ISSUE THREAD

**Issue by moveccr** [isaki68k/nono-issue#98]
nono on Ubuntu on VirtualBox on Windows で、VirtualBox の「マウス統合」が有効なとき、次のように挙動するようだ。

1. wxWindow::WarpPointer() でマウスポインタを移動させる
2. Ubuntu のマウスは一旦動く
3. すぐに Windows ホスト側のマウス位置に移動するため、マウス位置が戻る

「マウス統合」をオフにすれば動く。これはどうしようもないのでマニュアルに記載するか。

**Comment by isaki68k** [comment]
2021/12/30 書いてみた。
